services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    volumes:
      - ./minio-data:/minio-data/

    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console

  mongodb:
    image: mongo:8.3.4-noble
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-data:/mongo-data
    ports:
      - "27017:27017"   # API

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
      - "61613:61613"   # STOMP
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_ROOT_USERNAME:guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_ROOT_PASSWORD:guest}
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp;
      docker-entrypoint.sh rabbitmq-server"
